### ISSUE TITLE
When runing preprocess.py with Chinese dataset not get the same size or lenght

### ISSUE THREAD

**Issue by mrpeerat** [mokeam/Chinese-Word-Segmentation-in-NLP#4]
I running preprocess.py on Chinese Word segmentation dataset such as AS, pku 
But an input file or BIS file that return from preprocess.py does not get the same number of line and the same number of character, you can try with
python3 preprocess.py as_training.utf8 input_file.txt bis_file.txt
Then check the number of line in input_file.txt not the same as as_training.utf8 
And character position and length in bis_file.txt file is not the same as input_file.txt too

**Comment by mokeam** [comment]
it's probably because there is an empty new line at the end of input_file.txt. Just clear the new line and save the file, that's all.

**Comment by mrpeerat** [comment]
Probably not, as_training.utf8 had **708,953** lines and input_file.txt had **708,953** lines same as the original file with 9,077,003 characters but bis_file.txt had only **708,534** lines with **9,076,583** characters (the number of lines and characters on input_file and bis_file should be the same ?)
Because I running predict.py on input_file.txt and evaluate with score.py on bis_file.txt and output of predict.py there's error happened
_'AssertionError: Line 1326: lengths mismatch'_

**Comment by mokeam** [comment]
I just tried it on my system and there was no issue so I don’t know how i
can help you.

**Comment by mrpeerat** [comment]
Can you tell me a version for each library you use in this project, please?
Because now I think it might happen because of new version of library

**Comment by mokeam** [comment]
The compatibility is:
Python3.6.X,  Tensorflow 1.12.0

Can you send me a link to the dataset you are using? I could try it at my end for you. And i think it should be the same dataset that I am using so I don't understand why.

**Comment by mrpeerat** [comment]
I'm using dataset from http://sighan.cs.uchicago.edu/bakeoff2005/ (icwb2-data.rar [40 MB, md5])
And I select a file name as_training.utf8 on training folder

**Comment by mokeam** [comment]
Okay, I will try this again and check the score for you. If it works, I will send you the version of my libraries again.

**Comment by mokeam** [comment]
So I am currently running an old machine and TF won't compile on it. Sorry, I can't help you at this moment. The TF version I used in this project initially was 1.12.0 not 12.0. and Python3.6.X.

**Comment by mrpeerat** [comment]
It's ok, I think it's not about TF, because I had a problem with preprocess.py only (just only Academia Sinica and Peking University corpus that had a problem)
a predict.py file is fine

**Comment by mokeam** [comment]
Okay, you may want to modify the preprocess.py in order to cater for the corpus you're using.

**Comment by mrpeerat** [comment]
Can you try to run a preprocess.py with Academia Sinica and Peking University corpus training dataset, count a number of lines and characters in an input file and a BIES file is equal or not? and it's should be equal
(For me, it's not equal) :(

**Comment by mokeam** [comment]
I don't have reference link to the Corpus you are using. Like I said, you will only need to modify  some part of the codes. It could be that you have to add more things to the RegEx in the code like below:

`lines = [re.sub(r'\s(?=[^A-z0-9])','',line) for line in original_lines]`

`lines = [line.replace(" ","")for line in lines]`

`lines = [line.replace("\u3000","")for line in lines]`

That's all I can help with for now.

**Comment by mrpeerat** [comment]
I already upload the dataset that I had a problem on GitHub here (https://github.com/mrpeerat/CWS_corpus)
- as_training.utf8.zip is a training dataset that I want to preprocess with preprocess.py
- as_train_bis.txt is a BIES file from preprocess.py 
- as_train_inputfile.txt is a text input file from preprocess.py
as you can see the number of lines and characters on  as_train_bis.txt and as_train_inputfile.txt is not the same.
It should be the same number?
