### ISSUE TITLE
This model turns out pretty bad.

### ISSUE THREAD

**Issue by happy-nlp** [mokeam/Chinese-Word-Segmentation-in-NLP#5]
Sorry for my English.
I use CRF alone hits a F1-score more than 85%.
Your model's precision nerver reach 55%.
I can hardly believe that it was state-of-art.

**Comment by mokeam** [comment]
I never said this model was state of the art and this was an individual work so please do not discredit my work.

**Comment by boo-boos** [comment]
I am really sorry if I hurt you.
I tried to use my own dataset and it turn out not good.
I have high expectations for your model.
Maybe your model is pretty well in your dataset.
I read your source code today. I think you can try to add a CRF layer to make it better.

**Comment by happy-nlp** [comment]
I am really sorry if I hurt you.
I tried to use my own dataset and it turn out not good.
I have high expectations for your model.
Maybe your model is pretty well in your dataset.
